site_name: Python Dunder & Builtins
nav:
    - Landing: index.md
    - Objects, Values and Types:
        - 01 - Objects, Values and Types/placeholder.md
    - Standard Type Hierarchy:
        - 02 - Standard Type Hierarchy/placeholder.md
    - Dunder Methods:
        - Basic Configuration:
          - __new__: Dunder Methods/__new__.md
          - __init__: Dunder Methods/__init__.md
          - __del__: Dunder Methods/__del__.md
          - __repr__: Dunder Methods/__repr__.md
          - __str__: Dunder Methods/__str__.md
          - __bytes__: Dunder Methods/__bytes__.md
          - __format__: Dunder Methods/__format__.md
          - __hash__: Dunder Methods/__hash__.md
          - __bool__: Dunder Methods/__bool__.md
          - __lt__: Dunder Methods/__lt__.md
          - __le__: Dunder Methods/__le__.md
          - __eq__: Dunder Methods/__eq__.md
          - __ne__: Dunder Methods/__ne__.md
          - __gt__: Dunder Methods/__gt__.md
          - __ge__: Dunder Methods/__ge__.md
    - Builtins:
        - abs: Builtins/abs.md

theme:
  name: material

plugins:
    - search
    - mkdocstrings:
        default_handler: python
        handlers:
          python:
            selection:
              docstring_style: sphinx
            rendering:
              line_length: 88
              show_if_no_docstring: false
              merge_init_into_class: true
              show_source: false
              docstring_section_style: table
        watch:
          - asserto/
markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
copyright: Copyright &copy; 2016 - 2022 Simon Kerr
